<?php

/**
 * Fired when the plugin is uninstalled.
 *
 * When populating this file, consider the following flow
 * of control:
 *
 * - This method should be static
 * - Check if the $_REQUEST content actually is the plugin name
 * - Run an admin referrer check to make sure it goes through authentication
 * - Verify the output of $_GET makes sense
 * - Repeat with other user roles. Best directly by using the links/query string parameters.
 * - Repeat things for multisite. Once for a single site in the network, once sitewide.
 *
 * This file may be updated more in future version of the Boilerplate; however, this is the
 * general skeleton and outline for how the file should work.
 *
 * For more information, see the following discussion:
 * https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate/pull/123#issuecomment-28541913
 *
 * @link       https://www.chargebee.com
 * @since      1.0.0
 *
 * @package    Chargebee_Membership
 */

// If uninstall not called from WordPress, then exit.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}
// Clear database data generated by CB-Plugin.
global $wpdb;
// Delete CB API key on deletion of plugin.
delete_option( 'cbm_api_key' );
delete_option( 'cbm_site_name' );
delete_option( 'cbm_site_settings' );

// Delete account and general options.
delete_option( 'cbm_account' );
delete_option( 'cbm_general' );

// Delete transient cache.
delete_transient( 'cbm_level_product_data' );
delete_transient( 'cbm_restrict_taxonomies' );
delete_transient( 'cbm_restrict_post_types' );

// Delete usermeta.
$wpdb->query( "DELETE FROM {$wpdb->usermeta} WHERE meta_key='chargebee_user_id'" );
$wpdb->query( "DELETE FROM {$wpdb->usermeta} WHERE meta_key='chargebee_user_subscriptions'" );

// Delete postmeta.
$wpdb->query( "DELETE FROM {$wpdb->postmeta} WHERE meta_key='cbm_restrict_option'" );
$wpdb->query( "DELETE FROM {$wpdb->postmeta} WHERE meta_key='cbm_restrict_level'" );

// Delete custom table on uninstall.
$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}cbm_products" );
$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}cbm_levels" );
$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}cbm_level_relationships" );
$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}cbm_user_notification" );
